// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "index",
    "fundamentals",
    "trading",
    "settlement",
    {
      type: "category",
      label: "API Reference",
      collapsible: true,
      collapsed: true,
      link: { type: "generated-index", slug: "/api" },
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

export default sidebars;
